name: Docker Build and Push from Upstream Tag

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟检查一次上游仓库（可自定义）

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch upstream tags
      run: |
        # 获取上游仓库的最新 tags
        upstream_tags=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/nicoboss/nsz/tags)

        # 提取最新的 tag 名称
        latest_tag_name=$(echo "$upstream_tags" | jq -r '.[0].name // empty')
        echo "Latest upstream tag: $latest_tag_name"

        # 如果没有获取到 tag，则退出
        [ -z "$latest_tag_name" ] && exit 1

        # 将 tag 名称存储为环境变量
        echo "UPSTREAM_TAG=$latest_tag_name" >> $GITHUB_ENV

    - name: Checkout code at upstream tag
      uses: actions/checkout@v4
      with:
        repository: 'https://github.com/nicoboss/nsz'  # 指定上游仓库
        ref: ${{ env.UPSTREAM_TAG }}  # 检出上游最新 tag 对应的代码

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64,darwin/amd64,darwin/arm64  # 根据需要调整目标架构
        push: true
        tags: |
          zhengyongtao/nsz:$UPSTREAM_TAG

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
